### ISSUE TITLE
Data loss while prefect was not working for 5 days.

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#157]
For Sneha Commcare connector when prefect stopped; cursor keys seem to have weirdly updated and we missed updates atleast in cases for 5 days - see snapshots from commcare for a case that had updates on 03/31,04/30 and then it may end. the first two are reflected in case updates on airbyte staging schema and you can see two cases (this is before deduplication) but none in the time period.. we seem to have recoved after june 03 but five days of records were not recovered and we had to resync the whole thing again. 

Will have to test this on my end. 

<img width="878" alt="Screenshot 2023-06-13 at 4 15 32 PM" src="https://github.com/DevDataPlatform/DDP_backend/assets/9019958/757a144d-a664-4bf9-a8bd-ab53fc521518">

**Comment by nairabhishek73** [comment]
Hey what's the status of this
