### ISSUE TITLE
Schema changes whenever the org changes something in the form

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#284]
this is from the #283 only we need to resync the data.  So whenever the org changes the schema or something the sync fails. for sneha, they changed the name of the form or they removed it or something. We need a way to reset the data and this means it will clear out the data which is already in the tables and then will resync it. Then we can put more rules that only admin can do this but this can be done later.

**Comment by Ishankoradia** [comment]
Closing this since Dalgo now has the ability to auto-detect schema changes every night. A user can also do it manually fron the UI/their dashboard.
