### ISSUE TITLE
Select Airbyte cursor field

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#296]
![Image](https://github.com/DevDataPlatform/DDP_backend/assets/9019958/6815a3aa-b267-4184-98b4-3a0a4617357e)

so for LAHI we're using MySQL as a data source and MySQL has multiple cursor fields so in the UI we need to select one of them to be able to run the incremental sync

**Comment by nairabhishek73** [comment]
@fatchat lets talk about this today

**Comment by nairabhishek73** [comment]
Has this been tested?

**Comment by nairabhishek73** [comment]
Have you checked on LAHI data or some data where the default cursor field isn't the one we are selecting.
Then seeing if the data is being pulled as expected. 
If not could you ping @siddhant3030 and get his input.

**Comment by Ishankoradia** [comment]
I have tested the change of cursor field on our UI, updates the cursor field in airbyte. (which is what the feature does) 

Will ask siddhant what all streams are we pulling and test it.

**Comment by Ishankoradia** [comment]
@
<img width="1572" alt="Screenshot 2023-09-07 at 7 31 43 PM" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/8a0b671b-737f-4915-9ada-cb18f57e1396">

nairabhishek73 @siddhant3030 i have tested this out for random 4-5 streams. The data is being pulled. Let me know if there are some other tests we can do on the connector base on LAHI's use case.

**Comment by siddhant3030** [comment]
@Ishankoradia can you run the sync one more time for incremental sync

**Comment by siddhant3030** [comment]
Also I dont know which cursor field you have choose but I think i tested with updated_on but you can test

**Comment by Ishankoradia** [comment]
Okay great. @nairabhishek73 its been tested by siddhant also.
