### ISSUE TITLE
Not able to pull all the data from kobo.

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#308]
We're not able to pull all the raw data in staging. I think its because we're passing only these columns in schema. Somehow after the update that is not working. Ishan knows this

![Image](https://github.com/DevDataPlatform/DDP_backend/assets/9019958/2b89dfc3-528c-4adf-b3e6-8d0cccbba4d1)

**Comment by siddhant3030** [comment]
@fatchat let's keep this open. I'll try to find a solution for this and will also talk to airbyte team

**Comment by fatchat** [comment]
@siddhant3030 when can you talk to the airbyte team

@nairabhishek73 we need this before our next airbyte upgrade ... since our last upgrade was essentially forced upon us by airbyte

**Comment by siddhant3030** [comment]
@fatchat  let me ping them today. Will create an issue

**Comment by siddhant3030** [comment]
https://github.com/airbytehq/airbyte/issues/30027 

created the issue here

**Comment by fatchat** [comment]
in order to upgrade to airbyte >= 0.50 we need to update our custom connectors to declare the following schema
- _airbyte_id
- data
- cursor for incremental

the `data` field will be json data which we deserialize via dbt

closing this issue
