### ISSUE TITLE
No guidance around SSL when in fact no tunnel and disable are required.

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/DDP_backend#313]

**Comment by fatchat** [comment]
@nairabhishek73 something like this?

<img width="510" alt="image" src="https://github.com/DevDataPlatform/DDP_backend/assets/2160416/89e80f84-2321-403b-8d2f-92685463af73">

**Comment by nairabhishek73** [comment]
Is there a known scenario when they would pick something besides disable and no tunnel @siddhant3030

**Comment by fatchat** [comment]
Sure, but in those cases they know to enter that information. We only want to cover the easy case

**Comment by fatchat** [comment]
Let me see if I can set the defaults

**Comment by siddhant3030** [comment]
@nairabhishek73 we haven't tested this enough. We should this for LAHI atleast

**Comment by nairabhishek73** [comment]
Noted @siddhant3030 . @fatchat We can go with the option you suggsted. Just add an asterisk right next to the text. Then space and what you have in brackets.

**Comment by nairabhishek73** [comment]
Works
