### ISSUE TITLE
api to get embed token for usage dashboard

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/DDP_backend#349]
- For the issue https://github.com/DalgoT4D/docker-superset/issues/16 
- Add a column `superset_creds` to the Org table. This will have sercret_id of secrets managers to store the superset user creds.
- Create an endpoint POST `api/superset/embed_token/{dashboard_uuid}` that returns a token needed to embed a superset dashboard.

    - The api will internally hit the superset instance and call POST `api/v1/security/login` to get an `access_token`
    - Then it will call GET `api/v1/security/csrf_token` with Bearer auth as the above `access_token` to get a `csrf_token`
    - Finally use the `csrf_token` in the header (`X-CSRFToken`) and Bearer auth to fetch the embed token from superset. POST `api/v1/security/guest_token`. Check api documentation of superset for the right body data.

**Comment by Ishankoradia** [comment]
Have added the api to fetch the embed token for a dashboard @fatchat . 
Can you help in adding the RLS in the guest_token request ? There is a TODO: comment in the api.

**Comment by fatchat** [comment]
i thought the dashboard's uuid was hardcoded? i.e. in the .env?
