### ISSUE TITLE
Pipeline log was different for helen: SHRI

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#354]
Yesterday when Helen opened the Dalgo and on the pipeline overview page she couldn't see the last log for yesterday instead it was showing her last Saturday logs. So I asked her to log out and log in again but still it was giving her the same view. But surprisingly I could see the last logs. I asked her for the screenshot which is here please check that

<img width="995" alt="image" src="https://github.com/DalgoT4D/DDP_backend/assets/9019958/4ba8ca32-1ffe-44ca-9764-929b86e5698f">

**Comment by fatchat** [comment]
this was fixed in https://github.com/DalgoT4D/webapp/issues/423 can you ask her to reload / clear cache
