### ISSUE TITLE
error from switching pipeline overview to usage 

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#421]
When I try to switch from any page to usage dashboard page it gives me error. 

https://github.com/DalgoT4D/DDP_backend/assets/9019958/a10755c0-2b97-4d70-9050-3ccd45b38569

not on priority but something I noticed

**Comment by fatchat** [comment]
thanks this is a known error, will be fixed when the usage dashboard is released. we get emails from grafana every time it is triggered ...🤦🏽‍♂️🤦🏽‍♂️

will leave it on the sprint for this week since the usage dashboard is almost done

**Comment by Ishankoradia** [comment]
@fatchat agreed. The feature is not released yet, so when it does. We will run it for all orgs that subscribed to superset.

**Comment by Ishankoradia** [comment]
Nair: "Lets not show the `usage` tab" unless the feature is released.

**Comment by fatchat** [comment]
Fair point, but we're releasing this week I hope

**Comment by fatchat** [comment]
"central secret" done via https://github.com/DalgoT4D/DDP_backend/pull/427

**Comment by fatchat** [comment]
closing since #427 shows a better error message
usage dashboard not going out yet. will hide the menu item in a separate PR
