### ISSUE TITLE
Pipeline logs are not very useful to NGO user's

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#423]
Now in our product walkthrough, we give this explanation to a user where they can come to see these bars and figure out what's going on with their sync. If it fails, the user can check the logs and can see what's wrong but from the current logs, it's easier for us but not for them. We need a summarization of the logs and not the whole log. We can discuss but this is what I feel during the interaction with the SHRI team. 

<img width="1144" alt="Screenshot 2024-01-08 at 3 22 00 PM" src="https://github.com/DalgoT4D/DDP_backend/assets/9019958/b90ce7fa-9247-4084-aeb3-168f68fefd1f">

**Comment by fatchat** [comment]
agreed, this is covered by https://github.com/DalgoT4D/webapp/issues/440
