### ISSUE TITLE
Have role to just view usage dashboard

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/DDP_backend#472]
Asked by Abhishek from Sneha. He would like to share the usage dashboard with one of their team members but hide everything else like connections, warehouse, pipelines etc.

**Comment by fatchat** [comment]
@ashwinit4d how should we do this on the website, should we just hide the other menu items?

**Comment by ashwinit4d** [comment]
We should do this as a part of the feature - Role based platform access -   https://www.notion.so/openbrackets/Data-Privacy-and-Governance-7da15bb695ac4b8ab4bcd459896cdd07

Have updated the feature. We can hide the menu items depending on the user role. We can discuss further.
