### ISSUE TITLE
properly display name of warehouse on connection page

### ISSUE THREAD

**Issue by jakejh** [DalgoT4D/DDP_backend#516]
It's not a huge thing, but "bigquery-warehouse" is confusing.
<img width="1476" alt="Screenshot 2024-03-22 at 08 30 02" src="https://github.com/DalgoT4D/DDP_backend/assets/2295314/74a463e1-26ef-4b5a-9b4b-7c5ca603d4bc">
<img width="644" alt="Screenshot 2024-03-22 at 08 30 45" src="https://github.com/DalgoT4D/DDP_backend/assets/2295314/0479ad01-9593-440c-8079-80ab5a33aac3">

**Comment by fatchat** [comment]
good catch thank you
will fix
