### ISSUE TITLE
Two different behaviours of syncing of sources

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#520]
I have created three account so far and used the same db. But I see two different behaviours in both the account. 

1. In org Siddhant_test I see multiple schema's which has synced in the workflow. public, demostaging, airbyte_internal, prod, intermediate. 
2. In second org I see few schema's which is intermediate, prod. This org name is siddhant_new_test. 
3. I created another org siddhant_atecf_test and in this one I wanted staging schema to be sync so I though I will change default schema name in warehouse to staging. But after this I don't see any tables in the workflow. 

Why the behaviour is so different? what do I expect from this? I need a staging schema to be sync to test atecf account

cc: @nairabhishek73

**Comment by siddhant3030** [comment]
Seems like for every org it randomly syncs the data.

**Comment by fatchat** [comment]
@siddhant3030 we believe this has been fixed 
have released to staging
please try again

**Comment by siddhant3030** [comment]
This is fixed now. We can close this. thanks
