### ISSUE TITLE
unable to refresh source schema

### ISSUE THREAD

**Issue by jakejh** [DalgoT4D/DDP_backend#532]
the airbyte UI allows this in the replication tab, and sometimes tells me when the schema has changed before I ask.

is the only current option in dalgo to "reset" the connection?

**Comment by jakejh** [comment]
hmm, actually resetting the connection did not refresh the source schema. my particular source is a google sheet, and I changed the worksheet names, but dalgo still shows the old names.

**Comment by fatchat** [comment]
duplicate of https://github.com/DalgoT4D/webapp/issues/479
