### ISSUE TITLE
improper display of source in connection edit window

### ISSUE THREAD

**Issue by jakejh** [DalgoT4D/DDP_backend#533]
1. The source is called "CCP Program Monitoring Archive", not "Google Sheets".
2. I've already created this connection, so the title "Add a new connection" is inaccurate.

<img width="308" alt="Screenshot 2024-04-05 at 21 33 55" src="https://github.com/DalgoT4D/DDP_backend/assets/2295314/51f32a01-6e8d-4433-b08b-d1327c56de88">

**Comment by fatchat** [comment]
1. in`airbytehelpers:get_one_connection`, we need
```
    source_name = airbyte_conn["source"]["name"]
    destination_name = airbyte_conn["destination"]["name"]
```

2. https://github.com/DalgoT4D/webapp/issues/753

**Comment by fatchat** [comment]
<img width="627" alt="image" src="https://github.com/DalgoT4D/DDP_backend/assets/2160416/086c8023-80c0-400f-86b9-76c6efc7b851">
