### ISSUE TITLE
airbyte schema change detection 

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/DDP_backend#558]
### Motivation

For any organization, it is very common for the source schema to change. Some scenarios for schema changes could be

| Scenario  | Type | User journey | Airbyte handling |
| ------------- | ------------- | ------------- | ------------- |
| Add a new column | `Non-breaking change`  | Auto-propagate changes, doesn't require user's attention | Values for the new column will be filled in
| Remove a column | `Non-breaking change`  | Auto-propagate changes, doesn't require user's attention | The column will be removed from the destination
| Updated a data type of a column. `varchar` become `int4`  | `Non-breaking change`  | Auto-propagate changes, may or maynot require user's attentiob  | The data in the destination will remain the same. Any new or updated rows with incompatible data types will result in a row error in the raw Airbyte tables. In this case, a full resync of the connection is required.
| Add a new stream (eg. could be a new table in the database if source is postgres)  | `Non-breaking change`  | Auto-propagate changes, doesn't require user's attention | The next sync will create the new stream in the destination and fill all data in as if it is a historical sync
| Remove an existing stream  | `Non-breaking change`  | Auto-propagate changes, doesn't require user's attention | This stream(s) will stop updating. The data already synced will remain in the warehouse, can be removed manually
| Removed the cursor field on which incremental was happening  | `Breaking change`  | Requires user's attention  | Changes to reviews by user and be manually fixed, conneciton will need to be reset. 

### Inside Airbyte

The schema change detection is at a connection level. Airbyte gives you options on how to handle schema detection. You can instruct airbyte to take an action whenever the source schema is changed, these are options available 

- Ignore
- Pause connection
- Propagate column changes only
- Propagate all changes

Even though our replication frequency is set to `Manual` in airbyte (since we are orchestrating via Prefect), airbyte checks for any changes in your source schema immediately before syncing. 

`Breaking changes in airbyte UI`

<img width="668" alt="Screenshot 2024-04-19 at 12 27 18" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/413381f0-12e7-409f-a61e-375a77880355">

<img width="668" alt="Screenshot 2024-04-19 at 12 27 54" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/c14fc44f-ca03-46ac-85e7-f5b41807b5fc">

`Non-breaking changes in airbyte UI`

<img width="668" alt="Screenshot 2024-04-19 at 12 40 23" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/7e5af944-9e0a-4205-abdb-5b70d79e83c2">

<img width="668" alt="Screenshot 2024-04-19 at 12 40 32" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/496a692d-5b9d-41a0-9a37-2cfda5f4084d">

For Dalgo, we will use the following options

| Type | Airbyte option | Description
| ------------- | ------------- | -------------| 
| `Non-breaking` | `Propagate all changes` | Initially fixed but configurable and can be changed to `Pause connection` |
| `Breaking` | `Propagate all changes` | Although it doesn't matter what option we choose, since airbyte requires a compulsory user action here and syncs will be paused until changes are reviewed & applied.

Options for `Pause connection` and `Propagate all changes` (when source schema has changed) for a connection will kept configurable in Dalgo. In case of `Pause connection` and breaking changes, the pipelines will fail and report errors in prefect until changes are addressed. Below is a screenshot of how the error will look in prefect logs

<img width="1127" alt="Screenshot 2024-04-19 at 11 57 05" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/e9343ab6-8e7a-4904-b69c-ce708f9f27b3">

### Dalgo backend

1. Airbyte api config gives a flag for Dalgo to understand if there is any source schema change and if there is, of what type is it `no_change`┃`non_breaking`┃`breaking`. 

```
POST `/api/v1/web_backend/connections/get`
BODY {
    "connectionId": "<connection_id>"
}
RESPONSE {
      ...,
      ...,
      ...,
      "schemaChange": Enum(`no_change`┃`non_breaking`┃`breaking`)
}
```

2. To fetch and show the schema changes differences, we use the same api with the below post body.
Below is an example of how airbyte reports `breaking` schema changes in its api. The full schema of the `catalogDiff` can be found in their docs [here](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/web_backend/connections/get)

Below change was due to removal of a cursor field in an incremental sync. Also note the status of the sync, its `inactive` - airbyte converts the connections to `inactive` for breaking changes.
```
POST `/api/v1/web_backend/connections/get` 
BODY {
    "connectionId": "<connection_id>",
    "withRefreshedCatalog": true
}
RESPONSE {
      ...,
      ...,
      ...,
      "status": "inactive",
      "schemaChange": Enum(`no_change`┃`non_breaking`┃`breaking`),
      "catalogDiff": {
        "transforms": [
            {
                "transformType": "update_stream",
                "streamDescriptor": {
                    "name": "auth_user",
                    "namespace": "public"
                },
                "updateStream": [
                    {
                        "transformType": "remove_field",
                        "fieldName": [
                            "date_joined"
                        ],
                        "breaking": true,
                        "removeField": {
                            "schema": {
                                "format": "date-time",
                                "airbyte_type": "timestamp_with_timezone",
                                "type": "string"
                            }
                        }
                    }
                ]
            }
        ]
    },
}
```
3. Based on the `catalogDiff` in step 2. , Dalgo can show its users which stream has what sort of source schema changes for a connection. 

<img width="1396" alt="Screenshot 2024-04-19 at 13 46 20" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/dd6e1084-34c3-4bef-a97f-f7dd1fb60e2c">

On pressing `Review changes`, you will see this. The below airbyte UI is a bit non-intuitive to understand what exactly were the changes

<img width="672" alt="Screenshot 2024-04-19 at 13 43 47" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/68fa3069-b960-4d44-a595-934615f171cf">

Airbyte gives you a confirmation dialog after reviewing the changes and pressing `ok`. It recommends a reset of the data. Dalgo could skip this and force users to reset by giving them a different confirmation dialog. 

<img width="699" alt="Screenshot 2024-04-19 at 13 57 40" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/8d3386b4-e3ac-4ea2-881b-605dbcd6bf95">

After giving the confirmation, the streams are updated for that connection using
```
POST /v1/connections/update
BODY {
       ....,
       ....,
       .....,
       "syncCatalog": {
        "streams": [
            {
                ....
            }
        ]
    },
}
```
The `syncCatalog` here should be generated by applying `catalogDiff` (in step2.) to the old stream(s). 

4. Airbyte gives an option to trigger email notifications on schema changes if the option is switched on (pic below). By default, these go to the email to the creator of the workspace. The recepient email id can be updated. 

<img width="668" alt="Screenshot 2024-04-19 at 13 32 44" src="https://github.com/DalgoT4D/DDP_backend/assets/39583356/9f0234ae-7f5e-4ec1-95ce-4f509c1025fd">

Airbyte also allows slack notifications for schema updates. However, in case of Dalgo, we would ideally want to configure a custom webhook for schema updates and have the control over what to do with it. This is currently not possible in airbyte, this could be a good potential contribution by Dalgo to airbyte. 

We can run nightly jobs that checks for schema changes and send emails to the respective people in the org.

**Comment by Abhishek-N** [comment]
Subissues: #607 #599
