### ISSUE TITLE
create sendgrid email template with details of schema changes in a connection

### ISSUE THREAD

**Issue by Abhishek-N** [DalgoT4D/DDP_backend#598]
- [ ] Create a Sendgrid Email Template
- [ ] The template should have org name, all connections for that org that has schema changes, type of schema change i.e., breaking change or non breaking change (Figure out how to do a for loop inside an email template in sendgrid)
- [ ] A button that redirects to connections page
- [ ] A function in the backend that sends an email with above information

**Comment by fatchat** [comment]
the template won't have a list (because we don't know the length of the list), you will have to figure out how to iterate in the template language
