### ISSUE TITLE
remove old django management commands

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/DDP_backend#611]
1. `add-git-pull-blocks`
2. `createadminuser`
3. `run-tasks-migrate-cmd`
4. `set_uuids_in_orgtask_deployment`
5. `update-dataflow-type`
6. `update-org-dbt`
7. `updatepostgrescredentials`
8. `writedataflowblocks`

**Comment by fatchat** [comment]
@Ishankoradia can you look at the list above and let me know if any of them should not be removed

**Comment by Ishankoradia** [comment]
> @Ishankoradia can you look at the list above and let me know if any of them should not be removed

@fatchat maybe these also - i have never used them
`showentities`
`manage-user-attributes`
`deleteorg` - running on old models - either we delete or update.
`add-git-pull-blocks` - again running off old models.

**Comment by fatchat** [comment]
i'm going to keep `showentities` and `manage-user-attributes`
`deleteorg` will be updated via #613
