### ISSUE TITLE
Error while renaming a jsonb column in UI4t

### ISSUE THREAD

**Issue by mdshamoon** [DalgoT4D/DDP_backend#740]
<img width="842" alt="Screenshot 2024-07-03 at 3 30 08 PM" src="https://github.com/DalgoT4D/DDP_backend/assets/32592458/87b04dfe-cb4c-4b55-8472-dd683e92923f">

**Comment by fatchat** [comment]
this is strange, is it only for json columns?

**Comment by fatchat** [comment]
this happens when a rename is done after a drop in a sequence

**Comment by mdshamoon** [comment]
The issue was not because of the sequence but the column length. The issue arises when we have table with just one column. 

The SQL generated is as follows

```
--DBT AUTOMATION has generated this model, please DO NOT EDIT 
--Please make sure you dont change the model name 

{{ config(materialized='table', schema='intermediate') }}
WITH cte1 as (
SELECT "data"
FROM {{ source('staging', 'Food_Vendors_Onboarding') }}
) , cte2 as (
SELECT , "data" AS "pitjcc"
 FROM cte1
)
-- Final SELECT statement combining the outputs of all CTEs
SELECT *
FROM cte2
```

There is an extra comma after select which is not needed.

**Comment by fatchat** [comment]
understood, closing
