### ISSUE TITLE
create_elementary_report needs a --profile-target flag

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/DDP_backend#750]

**Comment by fatchat** [comment]
for antarang, we need to add `--profile-target` because for some reason it isn't `default`

step 1: figure out what's going on here
step 2: put the right target into the edr command line in `tasks.create_elementary_report` and `orgtaskfunctions.get_edr_send_report_task`

**Comment by Ishankoradia** [comment]
So the target in edr generation has the same meaning as dbt run. It points or refers to the configuration for connecting to the warehouse and the place where elementary tables are present. 

Clearly in case of antarang, someone update the `elementary_profiles/profiles.yml` and changed the `default` to `dalgo_DBT_Antarang_Foundation` under `outputs:`

To handle such cases, all we have to do is parse the `elementary_profiles/profiles.yml` file and figure out what is under `outputs:`. There can be more than one yes, so we randomly pick one for now until we expose this configuring elementary to the user.
