### ISSUE TITLE
convert the system dbt test task to a deployment

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/DDP_backend#803]
`dbt test` for some cases might take longer because of the size of the project and number of tests. Running it synchronously might time out and so we need to submit it to prefect as a deployment.

**Comment by fatchat** [comment]
Also need to do this for `dbt seed` which sometimes runs very long

**Comment by Ishankoradia** [comment]
@fatchat `dbt seed` is already running via deployment. 
We fixed when sneha needed to run their long `dbt seed` tasks
