### ISSUE TITLE
error locking tasks for deployment

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/DDP_backend#808]
```
 lock_tasks_for_pending_deployment - : failed to lock blocks for deployment 4e78a7df-e94a-463d-9dd4-70f043f63b0f, ignoring

lock_tasks_for_pending_deployment - : failed to lock blocks for deployment d68b82b2-b24b-4100-94fb-5c390c31b1b0, ignoring
```

**Comment by Ishankoradia** [comment]
Someone else was running it, so the `system user` couldn't lock it in the webhook

![Image](https://github.com/user-attachments/assets/d2d057fb-99b1-4adf-9227-dbb8684e7b04)

**Comment by Ishankoradia** [comment]
I am guessing something similar for the other deployment. 

![Image](https://github.com/user-attachments/assets/bc9ae35d-f089-44e3-9692-ff5bd459974b)

**Comment by Ishankoradia** [comment]
In both cases, can't say who triggered the pipeline. Would be nice to the orguser_id

**Comment by fatchat** [comment]
ok so it's not an error because the tasks are already locked

in`webhook_api.lock_tasks_for_pending_deployment` we are catching the exceptions thrown by `prefect_service.lock_tasks_for_deployment` ... so why is grafana seeing them

**Comment by Ishankoradia** [comment]
Hmmm, no idea. I need to check the alerting logic.

**Comment by fatchat** [comment]
Yes... not urgent it's just annoying because we get the emails

**Comment by fatchat** [comment]
no longer happening
