### ISSUE TITLE
check schema change detection for these connections

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/DDP_backend#809]
```
e28a1f8d-4875-462e-a70c-8418a890077b [agency-fund]
dd531e64-b658-4531-9ebc-8ec0b79bce16 [atecf]
abac540f-88c4-4bc8-9e32-6874b7d407f7
3483e1ca-df92-4dcb-821d-45d43d15f5c4
```

**Comment by Ishankoradia** [comment]
This is back again. I have asked airbyte people on the same thread that gives the solution to remove `airbyte_workspace`. 

I feel this could be something to do with the way we calculate & reconcile schema diffs manually. 
Since this comes and goes, maybe we reconcile it wrong sometimes.

**Comment by Ishankoradia** [comment]
Still getting the error (`Cannot invoke "io.airbyte.api.model.generated.AirbyteCatalog.getStreams()" because "discovered" is null`) for
- `dd531e64-b658-4531-9ebc-8ec0b79bce16` (glific source)
- `3483e1ca-df92-4dcb-821d-45d43d15f5c4` (papersurvey)

**Comment by Ishankoradia** [comment]
For the glific connection , i dont see any errors.

For the papersurvey, i still see the error`Cannot invoke "io.airbyte.api.model.generated.AirbyteCatalog.getStreams()" because "discovered" is null`
- 3483e1ca-df92-4dcb-821d-45d43d15f5c4 (papersurvey)
