### ISSUE TITLE
select schema changes to apply

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/DDP_backend#815]
When Airbyte gives us a list of schema changes to apply, the user's options are to either accept all or none. Dalgo does the same thing.

This ticket is to explore if it is possible to apply a selection of changes, and if so to implement the API for this.

**Comment by Ishankoradia** [comment]
Airbyte doesn't allow granular control over which schema changes to apply. Its either all or none.
For now we will just reset the affected streams.
