### ISSUE TITLE
deleting the warehouse and re-creating doesn't refresh the transformation prefect cli block

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/DDP_backend#836]

**Comment by fatchat** [comment]
CLI profile block creation is currently done in `orgtask_api.post_system_transformation_tasks`

- [ ] this function should attempt to retrieve `OrgPrefectBlockv1.objects.filter(block_type=DBTCLIPROFILE, ... )` first
- [ ] only if it doesn't exist should it attempt to create a new one
- [ ] creation of the new `OrgPrefectBlockv1` cli profile block should be pulled out into a separate function
- [ ] that separate function should attempt to fetch (by blockname) any potentially pre-existing Prefect block
- [ ] and only create a new Prefect block if required
- [ ] when a warehouse is re-created, attempt `gather_dbt_project_params` and if they exist then proceed with creating the new CLI profile block

**Comment by fatchat** [comment]
Warehouse and transformations should be loosely coupled now
