### ISSUE TITLE
ability to call dbt cloud api as part of pipelines

### ISSUE THREAD

**Issue by Ishankoradia** [DalgoT4D/DDP_backend#859]
This feature can be an elaborate one or a small one. We could do it in one of the two ways
1. [small] add the ability in piplines to call/configure 3rd party apis (here dbt cloud)
2. [long] add another type of user - "cloud user" having their project setup on dbt cloud

Dbt cloud should give some kind of a polling api for Dalgo (prefect) to make sure the dbt job is going to be completed/failed.

**Comment by fatchat** [comment]
https://docs.google.com/document/d/1xosQnlcMTCDzva83EAuAQk4DzdD2M3wEjpmq3j2rUfY/edit#heading=h.etmm7nhebdzd

**Comment by fatchat** [comment]
https://github.com/DalgoT4D/prefect-proxy/issues/161
